// Generated by gencpp from file beginner_tutorials/urmsg.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_URMSG_H
#define BEGINNER_TUTORIALS_MESSAGE_URMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace beginner_tutorials
{
template <class ContainerAllocator>
struct urmsg_
{
  typedef urmsg_<ContainerAllocator> Type;

  urmsg_()
    : header()
    , pickUpTime(0)
    , throwTime(0)  {
    }
  urmsg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pickUpTime(0)
    , throwTime(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _pickUpTime_type;
  _pickUpTime_type pickUpTime;

   typedef uint32_t _throwTime_type;
  _throwTime_type throwTime;





  typedef boost::shared_ptr< ::beginner_tutorials::urmsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::urmsg_<ContainerAllocator> const> ConstPtr;

}; // struct urmsg_

typedef ::beginner_tutorials::urmsg_<std::allocator<void> > urmsg;

typedef boost::shared_ptr< ::beginner_tutorials::urmsg > urmsgPtr;
typedef boost::shared_ptr< ::beginner_tutorials::urmsg const> urmsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::urmsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::urmsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'beginner_tutorials': ['/home/viktor/Desktop/3_sempro/MySqlROS/src/beginner_tutorials/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::urmsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::urmsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::urmsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::urmsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::urmsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::urmsg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::urmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a2e9cc88ef89af17cbcd6d11a52269cb";
  }

  static const char* value(const ::beginner_tutorials::urmsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa2e9cc88ef89af17ULL;
  static const uint64_t static_value2 = 0xcbcd6d11a52269cbULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::urmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/urmsg";
  }

  static const char* value(const ::beginner_tutorials::urmsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::urmsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint32 pickUpTime\n\
uint32 throwTime\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::beginner_tutorials::urmsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::urmsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pickUpTime);
      stream.next(m.throwTime);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct urmsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::urmsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::urmsg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pickUpTime: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.pickUpTime);
    s << indent << "throwTime: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.throwTime);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_URMSG_H
